### ISSUE TITLE
RectangleWaveform is not respecting activeColor and inactiveColor parameters

### ISSUE THREAD

**Issue by jlzapata** [rutvik110/flutter_audio_waveforms#15]
RectangleWaveform always show white bars regardless of the activeColor and inactiveColor parameters.

![image](https://user-images.githubusercontent.com/28404174/148873718-df59bf27-f936-4faa-9bdf-9bf1fb21c912.png)

Test only in android.

**Comment by rutvik110** [comment]
The white bars that you see is the borderWidth(*default to 1) of the rectangle overlapping the rectangle. This happens if you have a high sample rate with not enough width to display them properly in such case borderWidth overlapps the rectangle.
Try reducing the `totalSamples` that you're generating or reducing the borderWidth.
Let me know if you've any other doubt on this and if not I can go forward and close the issue.

**Comment by jlzapata** [comment]
Thanks @rutvik110. It was exactly what was happening. 

Thanks for the fast reply.
