### ISSUE TITLE
doesn't play with list of mp3 files from assets

### ISSUE THREAD

**Issue by mtertag** [rutvik110/flutter_audio_waveforms#19]
thank you for such amazing package 
i tried to play this package with list of mp3 files but it shows onely the first mp3 file , 
how can i use it with playable list ? or with anouther plugin like asset_audioplayer

**Comment by rutvik110** [comment]
Hey thanx! You should be able to play them! 
Have you gone through [the examples](https://github.com/rutvik110/flutter_audio_waveforms/blob/master/example/lib/main.dart)? They do demonstrate the usage with multiple audio files.

**Comment by mtertag** [comment]
thank you for your reply , i tried the same exemple you are using in github
but it shows onley one mp3 file ,
is it possible to make it compatible with asset audioplayer ?
thank you

**Comment by rutvik110** [comment]
I'm not able to understand what's the issue here! Music files are played through the assets itself! And I'm pretty sure there are audio files for each sample data for a music.
Btw, I'm gonna close this issue as it doesn't fall under the package usage actually but rather just related to playing music files in example.
