### ISSUE TITLE
[Feature] Add optional gradient color to waveforms

### ISSUE THREAD

**Issue by gdelataillade** [rutvik110/flutter_audio_waveforms#24]
Flutter version: 3.0.2
Package version: 1.2.1+6

I would be really awesome if we could fill the waveforms with a gradient color. I cloned your project and did this:

<img width="1680" alt="Screen Shot 2022-06-29 at 17 53 49" src="https://user-images.githubusercontent.com/32983806/176630437-6bcbc2b3-55d4-4bab-a14a-cd888971bdec.png">

What do you think ?

I would defenitly use this feature in my project. If you are interested I can create a Pull Request.

Thanks for your work.

**Comment by rutvik110** [comment]
This looks cool and indeed will be a nice addition.

There's two things I'm thinking about rn considering this lands in the package:

1.  I'm thinking about how could you reflect active portion of the waveform here? Yours current changes seems like only painting the static waveform but doesn't take the activeRatio into the account for showing the active waveform. 

2. Also, I think if we plan to support this then we'll need to make adjustments to control the gradient direction(left-right or top-bottom) through some exposed parameters to the user and update the LinearGradient based on those parameters instead of hardcoding the direction.

If you could add support for this changes, then that would be really great! If not, then that's totally fine. 
Feel free to make the PR and we can figure things out from there.🙌
Thanx!
